spring:
  data:
    solr:
      host: http://39.102.60.120:8080/solr
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.60.120:3306/hypermarket?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 39.102.60.120
    port: 5672
    username: wqk
    password: 123456
    virtual-host: /study
dubbo:
  application:
    name: search-service
  registry:
    address: 39.102.60.120:2181
    protocol: zookeeper
  protocol:
    port: 20882
server:
  port: 8012
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl