dubbo:
  application:
    name: product-service
  registry:
    address: 10.31.131.88:2181
    protocol: zookeeper
  protocol:
    port: 20881
server:
  port: 8011
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hypermarket?serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
