dubbo:
  application:
    name: detail-service
  registry:
    address: 39.102.60.120:2181
    protocol: zookeeper
  protocol:
    port: 20884
server:
  port: 8014
html:
  locations: E:\\html\\
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.60.120:3306/hypermarket?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 39.102.60.120
    port: 5672
    username: wqk
    password: 123456
    virtual-host: /study
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl