dubbo:
  application:
    name: index
  registry:
    protocol: zookeeper
    address: 39.102.60.120:2181
  consumer:
    timeout: 10000
server:
  port: 9012
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
