spring:
  data:
    solr:
      host: http://192.168.91.128:8080/solr
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hypermarket?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.91.128
    port: 5672
    username: wqk
    password: 123
    virtual-host: /study
dubbo:
  application:
    name: search-service
  registry:
    address: 10.31.131.88:2181
    protocol: zookeeper
  protocol:
    port: 20882
server:
  port: 8012
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl