dubbo:
  application:
    name: background
  registry:
    protocol: zookeeper
    address: 39.102.60.120:2181
  consumer:
    timeout: 10000
server:
  port: 9011
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: 39.102.60.120
    port: 5672
    username: wqk
    password: 123456
    virtual-host: /study
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 39.102.60.120:22122
image:
  server: http://39.102.60.120:9270/