dubbo:
  application:
    name: background
  registry:
    protocol: zookeeper
    address: 10.31.131.88:2181
  consumer:
    timeout: 10000
server:
  port: 9011
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: 192.168.91.128
    port: 5672
    username: wqk
    password: 123
    virtual-host: /study
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.91.128:22122
image:
  server: http://192.168.91.128/